directories:
  output: build
  buildResources: build
appId: com.chatui.app
productName: ChatUI
icon: assets/icon.png
files:
  - filter:
      - main.js
      - preload.js
      - backend/**/*
      - frontend/dist/**/*
      - assets/**/*
      - node_modules/**/*
asarUnpack:
  - backend/**/*
extraResources:
  - from: backend/node_modules
    to: backend/node_modules
mac:
  category: public.app-category.productivity
  target: dmg
win:
  target: nsis
linux:
  target: AppImage
electronVersion: 37.2.3
